version: '3.8'

services:
  todo-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    command: sh -c "npm start"
    restart: on-failure

  todo-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - todo-backend
    command: sh -c "sleep 5 && npm start"
    restart: on-failure
